// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ynjpaegzopecictucvhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluanBhZWd6b3BlY2ljdHVjdmhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NTU0MTYsImV4cCI6MjA2OTUzMTQxNn0.3aWP2zkFGdIQQIIlrikhrACmLCj_PLpJB5RMPb8NU8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);